spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/test"
    name: "test"
    username: "root"
    password: "password"
    driver-class-name : "org.mariadb.jdbc.Driver"
mybatis:
  config-location: "classpath:mybatis-config.xml"
